// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stgkqlllwziiwwqcjrcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0Z2txbGxsd3ppaXd3cWNqcmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4OTYyNzYsImV4cCI6MjA2MTQ3MjI3Nn0.WMgCFpk50nmdKfVm_Hlq1vi_baloWR93IshYsyZZ8rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);